"""Fix foreign key issue

Revision ID: 724bd57df623
Revises: 7affbe33c498
Create Date: 2025-05-18 08:55:55.191802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '724bd57df623'
down_revision = '7affbe33c498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['employer_id'], ['user_id'])
        batch_op.drop_column('posted_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_by', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employer_id')

    # ### end Alembic commands ###
