"""Increase role column length

Revision ID: e8c5f41fb68f
Revises: 096ac131323e
Create Date: 2025-05-05 12:20:31.950457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8c5f41fb68f'
down_revision = '096ac131323e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('job_seeker', 'employer', 'admin'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('job_seeker', 'employer', 'admin'),
               existing_nullable=False)

    # ### end Alembic commands ###
